<div class="ui grid" id="vue">
    <div class="ten wide centered column">
        <form class="ui form primary" method="POST">
            {{ csrf_field() }}
            <h4 class="ui dividing header primary text">Edit {{ $setting->name }} Setting</h4>
            <div class="field">
                <label for="estimate">Estimated Value</label>
                <div class="ui action input">
                    <input type="text" name="estimate" readonly="readonly" id="estimate"
                           value="{{ $setting->present()->estimatedValue }}" />
                    <button class="ui primary right labeled button" type="button" id="toggle" onclick="useEstimate()">
                        <span>Use This Value</span>
                    </button>
            </div>
            <p class="ui grey text">This value is a best guess generated by the system.  It should be pretty accurate, but always double check.</p>
                <div class="inline fields">
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="enabled" value="0" {{ $setting->enabled == 0 ? 'checked="checked"' : '' }} />
                            <label>Disabled</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="enabled" value="1" {{ $setting->enabled == 1 ? 'checked="checked"' : '' }} />
                            <label>Enabled</label>
                        </div>
                    </div>
                </div>
            <div class="field">
                <label for="value">Current Value</label>
                <input type="text" name="value" value="{{ $setting->value }}">
            </div>
            <input type="submit" class="ui primary button" value="Update setting" />
        </form>
    </div>
</div>

@section('js')
    <script>
        function useEstimate() {
            var estimate = $('#estimate').val();

            $('#value').val(estimate);
        }
    </script>
@endsection